"""Example visualization of AutoSpecNorm local normalization.

This script demonstrates how AutoSpecNorm performs local pseudo-continuum
normalization for one selected spectral line and one synthetic spectrum.

The figure contains three panels:

    1. The top panel compares the unnormalized observed spectrum, the locally
       normalized observed spectrum, the interpolated synthetic spectrum, the
       selected normalization points, the normalization uncertainty interval,
       the chi-square fitting window, and a vertical marker for the analyzed
       diagnostic line.

    2. The middle panel shows the local pseudo-continuum correction factor
       applied by AutoSpecNorm.

    3. The bottom panel shows the flux difference introduced by the local
       normalization. These diagnostic panels make small local corrections
       visible even when the observed spectrum is already well flattened.

Notes
-----
AutoSpecNorm performs best when the observed spectrum has already been
flattened or pseudo-continuum normalized and the synthetic spectrum is
continuum-normalized. Under these conditions, AutoSpecNorm mainly corrects
residual local pseudo-continuum differences between the observed and synthetic
spectra.

This script is intended as a compact example for testing and visualizing
AutoSpecNorm performance. Users should update the filenames, selected line
index, model spectrum, smoothing width, and plotting limits for their own data.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Tuple

import matplotlib.pyplot as plt
import numpy as np
from scipy.ndimage import gaussian_filter1d

from AutoSpecNorm_Regions import AutoSpecNorm_Regions


@dataclass(frozen=True)
class AutoSpecNormExampleConfig:
    """User configuration for the AutoSpecNorm example script."""

    # ------------------------------------------------------------------
    # Input files
    # ------------------------------------------------------------------

    # Observed stellar spectrum. The file must contain at least three columns:
    # wavelength, flux, and flux uncertainty. In this example, the observed
    # spectrum is assumed to be already flattened or pseudo-continuum
    # normalized.
    observed_spectrum_file: Path = Path("IGRINS_H_K_band_Flattened_Spectrum_GJ205.txt")

    # Line-list file containing species labels, line centers, radial velocities,
    # and fitting windows. This example visualizes one selected line from this
    # file.
    line_list_file: Path = Path("Species_Fit_Ranges_GJ205.txt")

    # Synthetic spectrum generated by Turbospectrum. The synthetic spectrum
    # should preferably be continuum-normalized before being analyzed with
    # AutoSpecNorm.
    model_spectrum_file: Path = Path("t3700_g+4.5_z+0.20_a+0.00_v1.00.mod")

    # ------------------------------------------------------------------
    # Selected line and wavelength settings
    # ------------------------------------------------------------------

    # Zero-based index of the diagnostic line to visualize from
    # Species_Fit_Ranges_GJ205.txt.
    #
    # For example:
    #
    #     0 = first row in the file
    #     1 = second row in the file
    #     2 = third row in the file
    #     ...
    #
    # The selected row defines the species name, central wavelength,
    # radial velocity, and chi-square fitting window used throughout
    # this example.
    selected_line_index: int = 12

    # Observed wavelengths are assumed to be stored in microns in this example.
    # Multiplying by 1e4 converts them to Angstroms.
    observed_wavelength_scale: float = 1.0e4

    # ------------------------------------------------------------------
    # Model smoothing and AutoSpecNorm parameters
    # ------------------------------------------------------------------

    # Gaussian smoothing sigma, in pixels, applied to the synthetic spectrum
    # before calling AutoSpecNorm. The default value was calibrated for IGRINS
    # spectra and should be modified for other instruments or resolutions.
    gaussian_sigma_pixels: float = 2.3

    # Half-width of the initial analysis region (AR) around the selected line.
    lam_diff_large: float = 3.0

    # Maximum number of internal AutoSpecNorm iterations used to expand the
    # analysis region (AR) or relax selection thresholds when needed.
    iteration_number: int = 25

    # Thresholds used by AutoSpecNorm to select candidate pseudo-continuum
    # points in the synthetic and observed spectra.
    limit_model: float = 0.95
    limit_star: float = 0.95
    peak_index_model: float = 0.002
    peak_index_star: float = 0.002

    # ------------------------------------------------------------------
    # Plot settings
    # ------------------------------------------------------------------

    output_figure_file: Path = Path("AutoSpecNorm_Performance_Diagnostics_GJ205.png")
    save_figure: bool = True
    show_figure: bool = True
    marker_size: float = 70.0


def read_observed_spectrum(
    path: Path,
    wavelength_scale: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Read observed wavelength, flux, and flux uncertainty arrays."""
    data = np.loadtxt(path)

    if data.ndim != 2 or data.shape[1] < 3:
        raise ValueError(
            f"Observed spectrum must contain at least three columns: {path}"
        )

    wavelength = data[:, 0] * wavelength_scale
    flux = data[:, 1]
    flux_error = data[:, 2]

    # Remove invalid values before passing the spectrum to AutoSpecNorm.
    valid = (
        np.isfinite(wavelength)
        & np.isfinite(flux)
        & np.isfinite(flux_error)
    )

    return wavelength[valid], flux[valid], flux_error[valid]


def read_line_list(
    path: Path,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Read species labels, line centers, radial velocities, and fit ranges."""
    species = []
    line_centers = []
    radial_velocities = []
    fit_minima = []
    fit_maxima = []

    with open(path, "r") as handle:
        for line in handle:
            parts = line.strip().split()
            if len(parts) < 5:
                continue

            species.append(parts[0])
            line_centers.append(float(parts[1]))
            radial_velocities.append(float(parts[2]))
            fit_minima.append(float(parts[3]))
            fit_maxima.append(float(parts[4]))

    if not line_centers:
        raise ValueError(f"No valid line-list entries were found in: {path}")

    return (
        np.asarray(species, dtype=str),
        np.asarray(line_centers, dtype=float),
        np.asarray(radial_velocities, dtype=float),
        np.asarray(fit_minima, dtype=float),
        np.asarray(fit_maxima, dtype=float),
    )


def read_and_smooth_model_spectrum(
    path: Path,
    gaussian_sigma_pixels: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """Read a synthetic spectrum and smooth it to the observed resolution."""
    data = np.loadtxt(path)

    if data.ndim != 2 or data.shape[1] < 2:
        raise ValueError(
            f"Synthetic spectrum must contain at least two columns: {path}"
        )

    wavelength = data[:, 0]
    flux = data[:, 1]

    valid = np.isfinite(wavelength) & np.isfinite(flux)
    wavelength = wavelength[valid]
    flux = flux[valid]

    # Smooth the synthetic spectrum so that its effective spectral resolution
    # and sampling more closely match those of the observed spectrum before
    # local normalization is performed.
    flux_smoothed = gaussian_filter1d(
        flux,
        sigma=gaussian_sigma_pixels,
        mode="nearest",
    )

    return wavelength, flux_smoothed


def run_autospecnorm_example(config: AutoSpecNormExampleConfig):
    """Run AutoSpecNorm for a selected diagnostic line and synthetic model.

    Returns
    -------
    tuple
        AutoSpecNorm output arrays together with the species name,
        diagnostic-line wavelength, and fitting-window boundaries.
    """
    (
        species,
        line_centers,
        radial_velocities,
        fit_minima,
        fit_maxima,
    ) = read_line_list(config.line_list_file)

    if config.selected_line_index >= len(line_centers):
        raise IndexError(
            "selected_line_index is outside the available line-list range."
        )

    lam_star, flux_star, err_flux_star = read_observed_spectrum(
        config.observed_spectrum_file,
        config.observed_wavelength_scale,
    )

    lam_model, flux_model = read_and_smooth_model_spectrum(
        config.model_spectrum_file,
        config.gaussian_sigma_pixels,
    )

    central_line = line_centers[config.selected_line_index]
    radial_velocity = radial_velocities[config.selected_line_index]

    species_name = species[config.selected_line_index]
    fit_minimum = fit_minima[config.selected_line_index]
    fit_maximum = fit_maxima[config.selected_line_index]

    autospecnorm_output = AutoSpecNorm_Regions(
        central_line,
        config.lam_diff_large,
        radial_velocity,
        lam_star,
        flux_star,
        err_flux_star,
        lam_model,
        flux_model,
        config.limit_model,
        config.limit_star,
        config.peak_index_model,
        config.peak_index_star,
        config.iteration_number,
    )

    return (*autospecnorm_output, species_name, central_line, fit_minimum, fit_maximum)


def plot_autospecnorm_result(config: AutoSpecNormExampleConfig) -> None:
    """Plot AutoSpecNorm output with separate correction diagnostic panels."""
    (
        lam_star_cut,
        flux_star_cut,
        flux_interp_model_cut,
        flux_star_cut_normalized_final,
        upper_flux_star_cut_normalized_final,
        lower_flux_star_cut_normalized_final,
        _err_flux_star_cut_normalized_final,
        lam_cut_work,
        _flux_star_cut_work,
        flux_interp_model_cut_work,
        delta,
        flag,
        species_name,
        central_line,
        fit_minimum,
        fit_maximum,
    ) = run_autospecnorm_example(config)

    if flag == 0:
        print("Warning: AutoSpecNorm did not find reliable normalization points.")

    print(f"Mean normalization uncertainty delta = {np.nanmean(delta):.6f}")

    # ------------------------------------------------------------------
    # High-contrast colors for the diagnostic figure
    # ------------------------------------------------------------------
    #
    # The colors below were chosen to make the main components easy to
    # distinguish on screen and in print:
    #
    #   - Gray dashed line: observed spectrum before local normalization.
    #   - Blue line: observed spectrum after local normalization.
    #   - Red line: interpolated synthetic spectrum.
    #   - Gold circles with black edges: selected normalization points.
    #   - Light-blue shaded region: normalization uncertainty interval.
    #
    # The bottom panel uses green and purple to distinguish the two
    # normalization-correction diagnostics.
    color_observed_raw = "0.45"
    color_observed_normalized = "tab:blue"
    color_model = "tab:red"
    color_points = "chartreuse"
    color_points_edge = "darkgreen"
    color_uncertainty = "lightsteelblue"
    color_normalization_function = "tab:green"
    color_flux_difference = "tab:purple"
    color_diagnostic_line = "black"
    color_fit_region = "orange"

    # ------------------------------------------------------------------
    # Normalization Correction Diagnostics
    # ------------------------------------------------------------------
    #
    # The normalization function represents the local correction applied by
    # AutoSpecNorm to the observed spectrum:
    #
    #     Normalization Function =
    #         Observed Flux / Normalized Observed Flux
    #
    # Values close to 1 indicate that only a small correction was required.
    # For spectra that are already well flattened, this correction function is
    # often close to unity across the entire analysis region.
    #
    # The quantity:
    #
    #     Normalized Flux - Original Flux
    #
    # directly shows the change introduced by the normalization procedure.
    normalization_function = flux_star_cut / flux_star_cut_normalized_final
    normalization_difference = flux_star_cut_normalized_final - flux_star_cut

    fig, (ax_spectrum, ax_correction, ax_difference) = plt.subplots(
        3,
        1,
        figsize=(9.2, 7.6),
        sharex=True,
        gridspec_kw={"height_ratios": [3.0, 1.0, 1.0]},
    )
    fig.subplots_adjust(
        left=0.12,
        right=0.96,
        top=0.93,
        bottom=0.09,
        hspace=0.10,
    )

    # ------------------------------------------------------------------
    # Top panel: observed spectrum, normalized spectrum, model, and points
    # ------------------------------------------------------------------
    #
    # The transparent vertical band marks the wavelength interval used for
    # chi-square fitting of the selected diagnostic line. The limits are read
    # from the last two columns of the species line-list file.
    ax_spectrum.axvspan(
        fit_minimum,
        fit_maximum,
        color=color_fit_region,
        alpha=0.18,
        label="Chi-square fitting window",
        zorder=0,
    )

    ax_spectrum.fill_between(
        lam_star_cut,
        lower_flux_star_cut_normalized_final,
        upper_flux_star_cut_normalized_final,
        color=color_uncertainty,
        alpha=0.55,
        label="Normalization uncertainty interval",
    )

    ax_spectrum.plot(
        lam_star_cut,
        flux_star_cut,
        color=color_observed_raw,
        linewidth=1.2,
        linestyle="--",
        label="Observed spectrum before local normalization",
    )

    ax_spectrum.plot(
        lam_star_cut,
        flux_star_cut_normalized_final,
        color=color_observed_normalized,
        linewidth=1.5,
        label="Observed spectrum after local normalization",
    )

    ax_spectrum.plot(
        lam_star_cut,
        flux_interp_model_cut,
        color=color_model,
        linewidth=1.4,
        label="Synthetic spectrum",
    )

    # Semi-transparent halo to make the selected normalization points stand
    # out clearly against the spectra and fitting-window shading.
    ax_spectrum.scatter(
        lam_cut_work,
        flux_interp_model_cut_work,
        s=config.marker_size * 2.2,
        marker="o",
        facecolors=color_points,
        edgecolors="none",
        alpha=0.25,
        zorder=4,
    )

    ax_spectrum.scatter(
        lam_cut_work,
        flux_interp_model_cut_work,
        s=config.marker_size,
        marker="o",
        facecolors=color_points,
        edgecolors=color_points_edge,
        linewidths=1.2,
        label="Selected normalization points",
        zorder=5,
    )

    # Mark the analyzed diagnostic line. The species label is taken from the
    # first column of the line-list file for the selected line index.
    spectrum_ymin_tmp, spectrum_ymax_tmp = ax_spectrum.get_ylim()
    line_top = spectrum_ymax_tmp - 0.18 * (spectrum_ymax_tmp - spectrum_ymin_tmp)

    ax_spectrum.vlines(
        central_line,
        ymin=spectrum_ymin_tmp,
        ymax=line_top,
        colors=color_diagnostic_line,
        linestyles=":",
        linewidth=1.3,
        zorder=4,
    )

    ax_spectrum.set_ylabel("Flux")
    ax_spectrum.set_title("AutoSpecNorm Local Normalization Diagnostic")
    # Display only the wavelength interval around the selected normalization
    # points, with 0.5 Angstrom padding on each side. This removes unrelated
    # parts of the extracted AR from the diagnostic figure and focuses the
    # plot on the region actually constrained by the normalization points.
    plot_minimum = np.nanmin(lam_cut_work) - 0.5
    plot_maximum = np.nanmax(lam_cut_work) + 0.5
    ax_spectrum.set_xlim(plot_minimum, plot_maximum)
    ax_spectrum.legend(fontsize=8, loc="lower left", frameon=True)
    ax_spectrum.tick_params(axis="both", which="major", labelsize=11)

    y_values = np.concatenate(
        [
            flux_star_cut,
            flux_star_cut_normalized_final,
            flux_interp_model_cut,
            lower_flux_star_cut_normalized_final,
            upper_flux_star_cut_normalized_final,
        ]
    )
    finite_y = y_values[np.isfinite(y_values)]
    if finite_y.size > 0:
        y_min = max(0.0, np.nanmin(finite_y) - 0.05)
        y_max = np.nanmax(finite_y) + 0.05
        ax_spectrum.set_ylim(y_min, y_max)

    # Label the analyzed diagnostic line. The vertical marker is truncated
    # below the label so the line does not pass through the annotation box.
    spectrum_ymin, spectrum_ymax = ax_spectrum.get_ylim()

    label_y = spectrum_ymax - 0.08 * (spectrum_ymax - spectrum_ymin)

    ax_spectrum.text(
        central_line,
        label_y,
        species_name,
        ha="center",
        va="center",
        fontsize=11,
        fontweight="bold",
        bbox=dict(
            facecolor="white",
            edgecolor="black",
            alpha=0.85,
            pad=2,
        ),
        zorder=6,
    )

    # ------------------------------------------------------------------
    # Middle panel: local pseudo-continuum correction factor
    # ------------------------------------------------------------------
    #
    # The correction factor is centered near 1. Values above or below 1 show
    # where AutoSpecNorm adjusted the local pseudo-continuum relative to the
    # original observed spectrum.

    ax_correction.plot(
        lam_star_cut,
        normalization_function,
        color=color_normalization_function,
        linewidth=1.5,
        label="Pseudo-continuum correction factor",
    )

    finite_correction = normalization_function[np.isfinite(normalization_function)]
    if finite_correction.size > 0:
        correction_padding = max(
            0.002,
            0.15 * (np.nanmax(finite_correction) - np.nanmin(finite_correction)),
        )
        ax_correction.set_ylim(
            np.nanmin(finite_correction) - correction_padding,
            np.nanmax(finite_correction) + correction_padding,
        )

    ax_correction.set_ylabel("Correction factor")
    ax_correction.legend(fontsize=8, loc="upper left", frameon=True)
    ax_correction.tick_params(axis="both", which="major", labelsize=11)

    # ------------------------------------------------------------------
    # Bottom panel: flux difference introduced by local normalization
    # ------------------------------------------------------------------
    #
    # This panel shows the difference between the normalized and original
# observed spectra and provides a direct visualization of the local
# correction introduced by AutoSpecNorm.

    ax_difference.plot(
        lam_star_cut,
        normalization_difference,
        color=color_flux_difference,
        linewidth=1.4,
        linestyle="--",
        label="Difference (Normalized - Original)",
    )

    finite_difference = normalization_difference[np.isfinite(normalization_difference)]
    if finite_difference.size > 0:
        difference_padding = max(
            0.002,
            0.15 * (np.nanmax(finite_difference) - np.nanmin(finite_difference)),
        )
        ax_difference.set_ylim(
            np.nanmin(finite_difference) - difference_padding,
            np.nanmax(finite_difference) + difference_padding,
        )

    ax_difference.set_xlabel("Wavelength (Angstrom)")
    ax_difference.set_ylabel("Normalized - Original")
    ax_difference.legend(fontsize=8, loc="lower left", frameon=True)
    ax_difference.tick_params(axis="both", which="major", labelsize=11)


    # ------------------------------------------------------------------
    # Align y-axis labels across all panels
    # ------------------------------------------------------------------
    #
    # Place all y-axis labels at the same horizontal position to improve
    # the visual appearance of the multi-panel figure.
    #
    label_x = -0.06

    ax_spectrum.yaxis.set_label_coords(label_x, 0.5)
    ax_correction.yaxis.set_label_coords(label_x, 0.5)
    ax_difference.yaxis.set_label_coords(label_x, 0.5)

    if config.save_figure:
        fig.savefig(config.output_figure_file, dpi=300, bbox_inches="tight")
        print(f"Saved figure: {config.output_figure_file}")

    if config.show_figure:
        plt.show()
    else:
        plt.close(fig)


def main() -> None:
    """Run the AutoSpecNorm example."""
    config = AutoSpecNormExampleConfig()
    plot_autospecnorm_result(config)


if __name__ == "__main__":
    main()
