"""=============================================================================
AutoSpecFit (ASF)
Automated Spectral Fitting Framework for Abundance Measurements
Version 1.0
=============================================================================

Author
------
Neda Hejazi

Overview
--------
AutoSpecFit (ASF) is an automated line-by-line spectral synthesis pipeline
designed for high-resolution elemental abundance measurements of cool stars.

The current ASF workflow proceeds as follows:
    1. Reading the observed stellar spectrum.
    2. Reading species-specific line-list files.
    3. Preparing abundance grids and launching Turbospectrum to generate
       synthetic spectra.
    4. Waiting for all required synthetic spectra to become available.
    5. Performing local pseudo-continuum normalization with AutoSpecNorm.
    6. Computing line-by-line chi-square abundance curves.
    7. Determining best-fit abundances and abundance uncertainties for
       individual spectral lines.
    8. Combining line abundances into species-level abundances through
       iterative rejection, clipping, and weighting procedures.
    9. Updating fixed elemental abundances between iterations and
       regenerating synthetic spectra when required.
   10. Writing final abundances and iteration results to output files.

Current Release
---------------
ASF v1.0 is designed for elemental abundance measurements assuming fixed stellar
atmospheric parameters supplied by the user. The current release does not automatically
optimize stellar parameters.

Required stellar atmospheric parameters include:

    - Effective temperature (Teff)
    - Surface gravity (log g)
    - Overall metallicity ([M/H])

Additional synthesis parameters may optionally be specified by the user:

    - Alpha enhancement ([alpha/Fe])
    - Microturbulent velocity (vmic)
    - Projected rotational velocity (vrot or vsini)

If these optional parameters are not provided, ASF adopts the default values
used in the Turbospectrum synthesis workflow:

    - [alpha/Fe] = +0.00
    - vmic = 1.00 km s^-1
    - vrot = 0.00 km s^-1

Users may modify these parameters as needed when generating synthetic spectra.

Future versions of ASF will include iterative stellar-parameter optimization
between abundance iterations to obtain self-consistent atmospheric parameters
and abundances.

AutoSpecNorm
------------
ASF uses AutoSpecNorm (ASN) for local pseudo-continuum normalization.
Local normalization is performed independently for every synthetic
spectrum tested during the chi-square fitting procedure rather than
using a single normalization for all trial abundances. This approach
allows the pseudo-continuum placement to adapt to abundance-dependent
changes in the synthetic spectrum and ensures that normalization and
abundance determination remain fully self-consistent.

ASN is implemented through two main routines:

    1. AutoSpecNorm_Regions
    2. AutoSpecNorm_Points

AutoSpecNorm_Regions identifies suitable spectral regions around each
spectral line and AutoSpecNorm_Points automatically identifies optimal
normalization wavelength data points within the selected regions and
determines the local pseudo-continuum placement.

The normalization uncertainty estimated by ASN is propagated
into the chi-square calculation used for abundance fitting, allowing
pseudo-continuum placement uncertainties to be incorporated into the
final abundance measurements.


ASF and its normalization module, ASN, have primarily
been developed and tested using flattened observed spectra and
continuum-normalized synthetic spectra generated by Turbospectrum. This
combination generally provides the most reliable local normalization,
chi-square fitting, and abundance measurements. Because the pseudo-continuum
in cool-star spectra depends on the strengths of nearby spectral features, ASF
re-evaluates the local normalization for every synthetic spectrum tested
during the chi-square fitting procedure, ensuring a self-consistent
comparison between the observed and synthetic spectra.

Turbospectrum Compatibility
---------------------------
ASF v1.0 has been developed and tested using Turbospectrum v15.1.

Synthetic spectra are generated externally through a custom bash script that
executes Turbospectrum v15.1 over a grid of elemental abundances. ASF does not
perform spectral synthesis directly. Instead, it prepares the abundance grids,
calls the Turbospectrum execution script, waits for the expected synthetic
spectra, and then performs normalization and abundance fitting.

Later versions of Turbospectrum may employ different execution methods or may
require modifications to the user-supplied bash script and the associated ASF
routines that launch, monitor, locate, and read the synthetic spectra. Users
working with newer Turbospectrum versions should verify compatibility and update
the ASF-Turbospectrum interface if required.

High-Performance Computing Systems
----------------------------------
ASF v1.0 has primarily been developed and tested on High-Performance Computing
(HPC) systems using a job scheduler such as SLURM.  Users running ASF on personal
computers, workstations, or non-SLURM systems may need to modify the ASF routines
responsible for submitting, monitoring, and waiting for Turbospectrum jobs.
In most cases, the Turbospectrum bash script itself does not need to be modified.

Scientific Publications and Citation
------------------------------------
AutoSpecFit has been developed and applied in:

    Hejazi et al. (2024), ApJ, 973, 31
    DOI: 10.3847/1538-4357/ad61dc

    Hejazi et al. (2025), AJ, 170, 18
    DOI: 10.3847/1538-3881/add696

Additional ASF applications are currently in preparation.


Abundance Scale and Conversion to [X/H]
<<<<<<< HEAD
------------------------------------
=======
--------------------------------------
>>>>>>> 2367185 (Revise tiered convergence criteria)
ASF abundances are reported as abundance offsets that must be combined with the
abundance pattern adopted in the input model atmosphere to obtain abundances on
the standard [X/H] scale.

For non-alpha elements, the final abundance is computed as:

[X/H] = [M/H]input + ASF(X)

For alpha elements (e.g., O, Mg, Si, Ca, and Ti), the alpha enhancement adopted
in the model atmosphere must also be included:

[X/H] = [M/H]input + [alpha/Fe]input + ASF(X)

where ASF(X) is the abundance offset measured by ASF for element X, [M/H]input is
<<<<<<< HEAD
the input metallicity supplied by the user, and [alpha/Fe]input is the input alpha-element
enhancement also provided by the user.
=======
=======
>>>>>>> 2367185 (Revise tiered convergence criteria)
the input metallicity supplied by the user, and [alpha/Fe]input is the input
alpha-element enhancement also provided by the user.

For example, for magnesium (Mg), which is an alpha element:

[M/H]input      = -0.30
[alpha/Fe]input = +0.12
ASF(Mg)         = +0.15

[Mg/H] = -0.30 + 0.12 + 0.15 = -0.03

The abundance notation and formulation adopted by ASF follow:

Hejazi, N., Lépine, S., Nordlander, T., Jao, W.-C., Coria, D. R., &
Lester, K. V. 2025, AJ, 170, 18

DOI: 10.3847/1538-3881/add696

"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
import logging
import time
import os
import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter1d

# AutoSpecNorm performs local pseudo-continuum normalization and returns the
# normalization uncertainty propagated into the abundance chi-square calculation.
from AutoSpecNorm_Regions import AutoSpecNorm_Regions


# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
LOGGER = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Configuration containers
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class StellarParameters:
    """Fixed stellar parameters used by ASF and Turbospectrum.

    ASF-Abund v1.0 treats these quantities as user-supplied inputs. They are
    used to construct synthetic-spectrum filenames and Turbospectrum execution
    strings. The current release does not optimize these parameters.
    """

    teff: str = "3700"
    logg: str = "+4.5"
    metallicity: str = "+0.20"
    alpha: str = "+0.00"
    vmic: str = "1.00"

    def base_model_stem(self) -> str:
        """Return the common filename stem for all synthetic spectra."""
        return (
            f"t{self.teff}_g{self.logg}_z{self.metallicity}"
            f"_a{self.alpha}_v{self.vmic}"
        )

    def parallel_parameter_string(self) -> str:
        """Construct the GNU-parallel parameter string for the fixed stellar parameters."""
        return (
            f" ::: {self.teff} ::: {self.logg} ::: {self.metallicity}"
            f" ::: {self.alpha} ::: {self.vmic}"
        )


@dataclass(frozen=True)
class SpeciesConfig:
    """Species and element labels used by the abundance pipeline.

    Users may modify or extend these lists to include additional atomic or
    molecular species depending on the wavelength coverage, line lists, target
    stars, and scientific goals of the analysis.

    When adding a new species, the corresponding species input file,
    Turbospectrum abundance grid, and synthetic spectra must also be available.
    """


    element_codes: Tuple[str, ...] = (
        "x08", "x12", "x13", "x19", "x20", "x22", "x24", "x25", "x26"
    )
    element_names: Tuple[str, ...] = (
        "O", "Mg", "Al", "K", "Ca", "Ti", "Cr", "Mn", "Fe"
    )
    species_names: Tuple[str, ...] = (
        "OH", "Mg", "Al", "K", "Ca", "Ti", "Cr", "Mn", "Fe"
    )

    def __post_init__(self) -> None:
        """Ensure all species-related arrays have the same length."""
        n_codes = len(self.element_codes)
        if len(self.element_names) != n_codes or len(self.species_names) != n_codes:
            raise ValueError("element_codes, element_names, and species_names must match in length.")

    @property
    def n_species(self) -> int:
        """Number of species/elements measured by the pipeline."""
        return len(self.species_names)


@dataclass(frozen=True)
class AutoSpecFitConfig:
    """Runtime configuration for AutoSpecFit-Abund.

    Edit this object rather than hard-coding paths, filenames, and analysis
    settings throughout the code. This centralizes user configuration and makes
    ASF easier to maintain, adapt, and reuse for different targets.
    """

    # ------------------------------------------------------------------
    # Input and output locations
    # ------------------------------------------------------------------

    # Observed stellar spectrum to be analyzed. The file must contain at least
    # three columns: wavelength, flux, and flux uncertainty. ASF assumes that
    # the observed spectrum has already been flattened or pseudo-continuum
    # normalized before the abundance analysis.
    observed_spectrum_file: Path = Path("IGRINS_H_K_band_Flattened_Spectrum_GJ205.txt")

    # Directory containing the synthetic spectra generated by Turbospectrum.
    # ASF waits for and reads the model spectra from this location.
    model_dir: Path = Path("/home/nedahejazi/Synthetic_Spectra/")

    # Directory where all ASF output products are written.
    output_dir: Path = Path(".")

    # ------------------------------------------------------------------
    # Species input files
    # ------------------------------------------------------------------

    # Species-specific line lists are loaded using:
    #
    #     f"{species_file_prefix}{species_name}{species_file_suffix}"
    #
    # Example:
    #
    #     Species_OH_H_K_band_GJ205.txt
    #
    # Each file should contain the selected diagnostic lines for one species.
    species_file_prefix: str = "Species_"
    species_file_suffix: str = "_H_K_band_GJ205.txt"

    # ------------------------------------------------------------------
    # Output files
    # ------------------------------------------------------------------

    # Human-readable line-by-line abundance log.
    #
    # Columns:
    #     LineCenter
    #     BestFit_Abundance_PolyFit
    #     BestFit_Abundance_Original
    #
    # This file is updated immediately after each line is fitted, allowing
    # users to monitor progress during long ASF runs.
    iteration_log_file: str = "ASF_LineByLine_Abundance_Iterations.txt"

    # Final elemental abundance table written after convergence or after the
    # last requested iteration.
    #
    # Columns:
    #     Element
    #     Final_Abundance
    #     Abundance_Error
    #     Final_Abundance_Not_Rounded
    #
    # The abundance error is calculated from the line-by-line chi-square
    # uncertainties of the same final or converged iteration.
    final_abundance_file: str = "ASF_Final_Elemental_Abundances.txt"

    # Prefix for iteration-level species abundance summaries.
    #
    # Example outputs:
    #     ASF_Species_Mean_Abundances_Iteration_1.txt
    #     ASF_Species_Mean_Abundances_Iteration_2.txt
    #
    # Each file records the abundance adopted for every species in that
    # iteration after line rejection, sigma clipping, and weighting.
    mean_abundance_prefix: str = "ASF_Species_Mean_Abundances_Iteration_"

    # ------------------------------------------------------------------
    # Turbospectrum model naming and execution
    # ------------------------------------------------------------------

    # Extension of the synthetic spectra generated by Turbospectrum.
    model_extension: str = ".mod"

    # Global switch controlling whether ASF launches Turbospectrum before
    # fitting. If this value is False, ASF assumes that all required synthetic
    # spectra already exist and only checks for the expected files.
    run_turbospectrum: bool = True

    # Optional per-iteration override for Turbospectrum execution.
    #
    # Examples:
    #     {}          -> use run_turbospectrum for every iteration
    #     {1: False} -> skip TS only for iteration 1
    #     {2: False} -> skip TS only for iteration 2
    #
    # This option is useful when restarting a partially completed run.
    run_ts_by_iteration: Dict[int, bool] = field(default_factory=dict)

    # User-supplied bash script used to execute Turbospectrum and generate
    # the synthetic spectra required by ASF.
    turbospectrum_runner: Optional[str] = "./run_TS_Interpolated_Model_H_band.sh"

    # Optional execution prefix used on HPC systems. The default reproduces
    # the original ASF workflow using SLURM and GNU parallel. Depending on the
    # system configuration, the "module load parallel" command may need to be
    # modified or removed. For direct execution on a local machine, set this
    # value to an empty string: "".
    turbospectrum_execution_prefix: str = "module load parallel; sbatch parallel"

    # Waiting behavior after Turbospectrum jobs are submitted.
    wait_for_models: bool = True
    max_model_wait_checks: int = 150
    model_wait_seconds: float = 0.5 * 3600

    # ------------------------------------------------------------------
    # Wavelength and abundance-grid settings
    # ------------------------------------------------------------------

    # Multiplicative factor applied to observed wavelengths. Use 1e4 to convert
    # microns to Angstroms when observed spectra are stored in microns.
    observed_wavelength_scale: float = 1.0e4

    # Abundance grid, in dex, used for synthetic-spectrum generation and
    # line-by-line chi-square fitting.
    #
    # During each ASF iteration, the abundance of the target element is varied
    # over this grid, while the abundances of all other elements are fixed to
    # the species-level mean abundances determined in the previous iteration.
    #
    # The default grid spans -0.35 to +0.35 dex in steps of 0.01 dex. Users may
    # freely modify both the abundance range and the grid spacing depending on
    # their scientific goals and computational resources.
    #
    # A finer grid generally provides smoother chi-square curves and more
    # precise abundance interpolation, but requires a larger number of
    # synthetic spectra and longer execution times. Conversely, a coarser
    # grid (e.g., 0.02 dex or larger steps) reduces the number of synthetic
    # spectra that must be generated and can substantially decrease the total
    # runtime of ASF.
    #
    # Users should ensure that the abundance range is sufficiently broad so
    # that the chi-square minimum does not occur near the grid boundaries.
    abundance_values: Tuple[float, ...] = tuple(np.round(np.arange(-0.35, 0.351, 0.01), 3))

    # ------------------------------------------------------------------
    # Iteration and convergence settings
    # ------------------------------------------------------------------

    # The first abundance iteration is run separately. This value gives the
    # number of additional iterations after iteration 1. The default value of
    # 11 gives a maximum of 12 total abundance iterations, limiting the
    # computational load on shared HPC systems.
    n_followup_iterations: int = 11

<<<<<<< HEAD
    # ASF convergence is evaluated between two consecutive iterations.
    # Standard convergence requires all species to change by <=
    # convergence_tolerance. If exactly one species remains non-converged while
    # all other species satisfy this threshold, ASF treats that species as an
    # oscillating element and adopts the average of its final two finite
    # iteration abundances as the final value.
    convergence_tolerance: float = 0.04



    # Late-iteration fallback convergence settings. These are used only after
    # fallback_start_iteration if strict convergence has not been reached.
    # ASF may accept the solution when at least minimum_converged_fraction of
    # species satisfy the convergence tolerance and the remaining species show
    # bounded, non-monotonic late-iteration behavior.
    minimum_converged_fraction: float = 0.70
    fallback_start_iteration: int = 10
    late_history_window: int = 3
    late_history_peak_to_peak_limit: float = 0.08
    require_non_monotonic_late_history: bool = True
=======
    # Tiered convergence settings used by ASF.
    #
    # Iterations 2-6:
    #     strict convergence is accepted only when all species change by
    #     <= early_convergence_tolerance between consecutive iterations.
    #
    # Iterations 7-8:
    #     convergence is accepted when all species, or all but one species,
    #     change by <= intermediate_convergence_tolerance. If one species is
    #     still non-converged, its final abundance is set to the median of its
    #     final three finite iteration abundances.
    #
    # Iterations 9-12:
    #     convergence is evaluated in the same way as iterations 7-8, but using
    #     late_convergence_tolerance.
    #
    # At the maximum iteration, if no convergence condition has been met, ASF
    # writes the final table using the last iteration for converged species and
    # the median of the final three finite iterations for non-converged species.
    early_convergence_tolerance: float = 0.03
    intermediate_convergence_tolerance: float = 0.04
    late_convergence_tolerance: float = 0.05
    intermediate_convergence_start_iteration: int = 7
    late_convergence_start_iteration: int = 9
    final_statistics_window: int = 3
>>>>>>> 2367185 (Revise tiered convergence criteria)


    # ------------------------------------------------------------------
    # AutoSpecNorm and model-smoothing settings
    # ------------------------------------------------------------------

    # Gaussian smoothing sigma, in pixels, applied to synthetic spectra to
    # match the resolution of the observed spectrum before fitting. The default
    # value of 2.3 pixels was calibrated for IGRINS spectra and should be
    # adjusted when analyzing data from other instruments or resolutions.
    gaussian_sigma_pixels: float = 2.3

    # Wavelength interval used by AutoSpecNorm when searching around each line.
    lam_diff_large: float = 3.0

    # AutoSpecNorm thresholds for identifying suitable normalization regions
    # and continuum/pseudo-continuum points.
    limit_model: float = 0.95
    limit_star: float = 0.95
    peak_index_model: float = 0.002
    peak_index_star: float = 0.002

    # Maximum number of internal AutoSpecNorm iterations.
    autospecnorm_iteration_number: int = 25

    # ------------------------------------------------------------------
    # Line rejection, uncertainty, and abundance-combination settings
    # ------------------------------------------------------------------

    # Sigma-clipping threshold applied to line-by-line abundances. For species
    # with small numbers of lines, ASF keeps the original values to avoid
    # over-clipping sparse diagnostics.
    sigma_clipping: float = 1.0

    # Half-width in dex around the sampled chi-square minimum used for local
    # parabolic fitting and chi2_min + 1 uncertainty estimation.
    parabolic_fit_half_width: float = 0.10

    # Abundance-grid edge rejection limits. OH lines use a more restrictive
    # lower limit because their abundance measurements can become less reliable
    # near the lower boundary of the tested grid.
    oh_lower_rejection_limit: float = -0.23
    generic_lower_rejection_limit: float = -0.34
    upper_rejection_limit: float = 0.34

    def abundance_strings(self) -> List[str]:
        """Return abundance values formatted with explicit signs for filenames."""
        return [f"{value:+.3f}" for value in self.abundance_values]

@dataclass
class LineList:
    """Selected spectral-line data for one species.

    Each line-list file provides the central wavelength, radial-velocity
    correction, and local fitting window for every selected diagnostic line.
    """

    species_labels: List[str]
    line_centers: np.ndarray
    radial_velocities: np.ndarray
    fit_min_wavelengths: np.ndarray
    fit_max_wavelengths: np.ndarray

    @property
    def n_lines(self) -> int:
        """Number of selected lines for this species."""
        return len(self.line_centers)


@dataclass
class LineFitResult:
    """Abundance-fit result for one selected spectral line.

    The object stores both the grid-based best abundance and the abundance
    inferred from a local parabolic fit to the chi-square curve.
    """

    species_name: str
    line_index: int
    line_center: float
    best_abundance_grid: float
    best_abundance_parabola: float
    abundance_error: float
    chi2_curve: np.ndarray

    @property
    def label(self) -> str:
        """Column label used in iteration-wide chi-square tables."""
        return f"{self.species_name}_{self.line_index + 1}"


@dataclass
class SpeciesIterationResult:
    """Combined abundance result for one species in one ASF iteration.

    The final species abundance is computed from accepted line-by-line
    abundances after edge rejection, conservative sigma clipping, and
    median-distance weighting.
    """

    species_name: str
    element_name: str
    line_results: List[LineFitResult]
    clipped_line_abundances: np.ndarray
    mean_abundance: float
    rounded_mean_abundance: float


# -----------------------------------------------------------------------------
# Input/output helpers
# -----------------------------------------------------------------------------

def read_observed_spectrum(path: Path, wavelength_scale: float) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Read observed wavelength, flux, and flux-error arrays.

    Parameters
    ----------
    path
        Text file with three columns: wavelength, flux, and flux error.
    wavelength_scale
        Multiplicative factor applied to the wavelength column.  Use 1e4 to
        convert microns to Angstrom.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Observed spectrum file not found: {path}")

    data = np.loadtxt(path)
    if data.ndim != 2 or data.shape[1] < 3:
        raise ValueError(f"Observed spectrum must have at least 3 columns: {path}")

    lam_star = data[:, 0] * wavelength_scale
    flux_star = data[:, 1]
    err_flux_star = data[:, 2]
    return lam_star, flux_star, err_flux_star


def read_species_line_file(path: Path) -> LineList:
    """Read one species line-list file.

    Expected columns after the header line are:
    species_label, line_center, radial_velocity, fit_min_wavelength,
    fit_max_wavelength.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Species line file not found: {path}")

    table = pd.read_csv(path, delim_whitespace=True, comment="#", skiprows=1, header=None)
    if table.shape[1] < 5:
        raise ValueError(f"Species file must contain at least 5 columns: {path}")

    return LineList(
        species_labels=table.iloc[:, 0].astype(str).tolist(),
        line_centers=table.iloc[:, 1].astype(float).to_numpy(),
        radial_velocities=table.iloc[:, 2].astype(float).to_numpy(),
        fit_min_wavelengths=table.iloc[:, 3].astype(float).to_numpy(),
        fit_max_wavelengths=table.iloc[:, 4].astype(float).to_numpy(),
    )


def read_all_line_lists(config: AutoSpecFitConfig, species: SpeciesConfig) -> List[LineList]:
    """Read line-list files for all species defined in ``SpeciesConfig``."""
    line_lists: List[LineList] = []
    for species_name in species.species_names:
        filename = f"{config.species_file_prefix}{species_name}{config.species_file_suffix}"
        line_lists.append(read_species_line_file(Path(filename)))
    return line_lists


def read_model_spectrum(path: Path, gaussian_sigma_pixels: float) -> Tuple[np.ndarray, np.ndarray]:
    """Read and smooth a synthetic spectrum.

    The synthetic spectrum is expected to contain at least two columns:
    wavelength and flux. The synthetic spectra generated by Turbospectrum
    should preferably be continuum-normalized before being analyzed with ASF.
    The model flux is smoothed to approximately match the resolution and
    sampling of the observed spectrum before fitting.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Synthetic spectrum not found: {path}")

    data = np.loadtxt(path)
    if data.ndim != 2 or data.shape[1] < 2:
        raise ValueError(f"Synthetic spectrum must have at least 2 columns: {path}")

    lam_model = data[:, 0]
    flux_model = gaussian_filter1d(data[:, 1], sigma=gaussian_sigma_pixels, mode="nearest")
    return lam_model, flux_model


def write_iteration_chi2_table(
    iteration_id: int,
    abundances: np.ndarray,
    line_results: List[LineFitResult],
    output_dir: Path,
) -> None:
    """Save chi-square curves for all fitted lines in one iteration.

    The output has one row per tested abundance and one column per spectral
    line. Example columns are: abundance, OH_1, OH_2, Mg_1, Fe_1.
    Failed or skipped abundance points are written as NaN.
    """
    if not line_results:
        LOGGER.warning("No chi-square curves were saved for iteration %s.", iteration_id)
        return

    chi2_columns = [result.chi2_curve for result in line_results]
    line_labels = [result.label for result in line_results]
    table = pd.DataFrame(
        np.column_stack([abundances, *chi2_columns]),
        columns=["abundance", *line_labels],
    )

    output_path = Path(output_dir) / f"Chi2_Iteration_{iteration_id}.txt"
    table.to_csv(output_path, sep=" ", index=False, float_format="%.6f", na_rep="nan")
    LOGGER.info("Wrote chi-square table: %s", output_path)


def write_iteration_abundance_error_table(
    iteration_id: int,
    line_results: List[LineFitResult],
    output_dir: Path,
) -> None:
    """Save line-by-line abundance uncertainties for one iteration.

    Uncertainties are estimated from local parabolic fits to chi-square as a
    function of abundance using the criterion chi2 = chi2_min + 1.
    """
    if not line_results:
        LOGGER.warning("No abundance errors were saved for iteration %s.", iteration_id)
        return

    table = pd.DataFrame(
        [[result.abundance_error for result in line_results]],
        columns=[result.label for result in line_results],
    )
    output_path = Path(output_dir) / f"Abundance_Errors_Iteration_{iteration_id}.txt"
    table.to_csv(output_path, sep=" ", index=False, float_format="%.6f", na_rep="nan")
    LOGGER.info("Wrote abundance-error table: %s", output_path)


def write_species_mean_table(
    iteration_id: int,
    species: SpeciesConfig,
    mean_abundances: np.ndarray,
    config: AutoSpecFitConfig,
) -> None:
    """Save species-level mean abundances for one iteration.

    The abundances written here are the iteration-level values used as fixed
    abundances for the next ASF iteration.
    """
    output_path = Path(config.output_dir) / f"{config.mean_abundance_prefix}{iteration_id}.txt"
    table = pd.DataFrame(
        {
            "element": species.element_names,
            "mean_abundance": mean_abundances,
        }
    )
    table.to_csv(output_path, sep=" ", index=False, header=False, float_format="%.6f")
    LOGGER.info("Wrote species mean-abundance table: %s", output_path)


def write_final_abundance_table(
    final_not_rounded: np.ndarray,
    final_rounded: np.ndarray,
    final_errors: np.ndarray,
    species: SpeciesConfig,
    config: AutoSpecFitConfig,
    nan_replacement_notes: Optional[List[str]] = None,
) -> None:
    """Save the final elemental abundance table.

    The table is written after convergence, or after the maximum requested
    number of iterations if formal convergence is not reached.

    The abundance errors are derived from the line-by-line chi-square
    uncertainties of the same iteration used for the final abundance solution.
    If NaN abundance values were replaced during model generation, the
    replacement history is appended as commented lines at the end of the file.
    """
    output_path = Path(config.output_dir) / config.final_abundance_file
    table = pd.DataFrame(
        {
            "Element": species.element_names,
            "Final_Abundance": final_rounded,
            "Abundance_Error": final_errors,
            "Final_Abundance_Not_Rounded": final_not_rounded,
        }
    )
    table.to_csv(output_path, sep=" ", index=False, header=True, float_format="%.6f")

    if nan_replacement_notes:
        with open(output_path, "a") as handle:
            handle.write("\n# NaN abundance replacements used during follow-up model generation\n")
            for note in nan_replacement_notes:
                handle.write(f"# {note}\n")

    LOGGER.info("Wrote final abundance table: %s", output_path)


def species_abundance_errors_from_iteration(
    species_results: List[SpeciesIterationResult],
) -> np.ndarray:
    """Return one abundance error per species for the current iteration.

    Each line-level abundance error is obtained from the local chi-square
    parabola using chi2 = chi2_min + 1. The species-level value written to the
    final abundance file is the median of the finite line-level errors from
    the same iteration used for the final abundance solution.
    """
    species_errors: List[float] = []

    for result in species_results:
        line_errors = np.asarray(
            [line.abundance_error for line in result.line_results],
            dtype=float,
        )
        finite_errors = line_errors[np.isfinite(line_errors)]

        if len(finite_errors) == 0:
            species_errors.append(np.nan)
        else:
            species_errors.append(float(np.nanmedian(finite_errors)))

    return np.asarray(species_errors, dtype=float)



def append_nan_replacement_notes_to_mean_file(
    iteration_id: int,
    notes: List[str],
    config: AutoSpecFitConfig,
) -> None:
    """Append NaN-replacement notes to the affected species-mean file.

    Notes are written as commented lines so the numerical table remains easy
    to read with tools that ignore lines beginning with ``#``.
    """
    if not notes:
        return

    output_path = Path(config.output_dir) / f"{config.mean_abundance_prefix}{iteration_id}.txt"

    with open(output_path, "a") as handle:
        handle.write("\n# NaN abundance replacements used for the next iteration\n")
        for note in notes:
            handle.write(f"# {note}\n")


# -----------------------------------------------------------------------------
# Model filename and Turbospectrum helpers
# -----------------------------------------------------------------------------

def build_model_filename(
    stellar_parameters: StellarParameters,
    element_abundances: Dict[str, str],
    model_extension: str,
) -> str:
    """Build one expected Turbospectrum synthetic-spectrum filename.

    Parameters
    ----------
    stellar_parameters
        Fixed stellar parameters used in the model filename stem.
    element_abundances
        Mapping from element code, e.g. ``x26``, to abundance string, e.g.
        ``+0.120``.  The order is preserved by normal Python dictionaries in
        Python 3.7+; the caller should construct the dictionary in the desired
        filename order.
    model_extension
        Filename extension, usually ``.mod``.
    """
    stem = stellar_parameters.base_model_stem()
    abundance_part = "".join(f"_{code}{abundance}" for code, abundance in element_abundances.items())
    return f"{stem}{abundance_part}{model_extension}"


def first_iteration_model_paths(
    config: AutoSpecFitConfig,
    stellar_parameters: StellarParameters,
    species: SpeciesConfig,
) -> List[List[Path]]:
    """Return model paths for iteration 1.

    In iteration 1, only one element abundance varies in each synthetic grid.
    """
    abundance_strings = config.abundance_strings()
    all_paths: List[List[Path]] = []
    for element_code in species.element_codes:
        species_paths = []
        for abundance in abundance_strings:
            filename = build_model_filename(
                stellar_parameters,
                {element_code: abundance},
                config.model_extension,
            )
            species_paths.append(Path(config.model_dir) / filename)
        all_paths.append(species_paths)
    return all_paths


def followup_iteration_model_paths(
    config: AutoSpecFitConfig,
    stellar_parameters: StellarParameters,
    species: SpeciesConfig,
    previous_abundance_strings: List[str],
) -> List[List[Path]]:
    """Return model paths for iteration >= 2.

    For a target species, its abundance is varied over the grid while the
    abundances of all other species are fixed to the previous iteration values.

    Important
    ---------
    The filename order intentionally follows the original ASF code: all fixed
    elements are appended first, in species-list order, and the target/variable
    element is appended last.  This order must match the Turbospectrum parallel
    command generated by ``followup_iteration_turbospectrum_commands``; otherwise
    ASF would wait for filenames that differ from the files generated by the
    synthesis script.
    """
    abundance_strings = config.abundance_strings()
    all_paths: List[List[Path]] = []

    for target_idx, target_code in enumerate(species.element_codes):
        species_paths = []
        for trial_abundance in abundance_strings:
            abundance_map: Dict[str, str] = {}

            # Append all fixed abundances from the previous iteration first.
            for idx, code in enumerate(species.element_codes):
                if idx != target_idx:
                    abundance_map[code] = previous_abundance_strings[idx]

            # Append the target element with the trial abundance last.
            abundance_map[target_code] = trial_abundance

            filename = build_model_filename(stellar_parameters, abundance_map, config.model_extension)
            species_paths.append(Path(config.model_dir) / filename)
        all_paths.append(species_paths)

    return all_paths


def build_turbospectrum_parallel_string(
    stellar_parameters: StellarParameters,
    variable_element_code: str,
    variable_abundance_strings: List[str],
    fixed_element_abundances: Optional[Dict[str, str]] = None,
) -> str:
    """Build the GNU-parallel argument string passed to the TS script.

    This function intentionally reproduces the string construction used in
    the original ASF script.  The exact underscore placement and ``:::``
    spacing are preserved because the external Turbospectrum bash script and
    GNU parallel command expect this format.

    Original ASF pattern for iteration 1:

        starting_str + space + e_str + middle_str + space_new + ' ' + abund_str_long

    Original ASF pattern for later iterations:

        starting_str + middle_str_new + space_new + ' ' + abund_str_long

    In both cases, the variable element is appended last and receives the full
    abundance grid.  Any fixed elements from the previous ASF iteration are
    inserted before the variable element.
    """
    fixed_element_abundances = fixed_element_abundances or {}

    # Preserve the original ASF command stem used by the external
    # Turbospectrum execution script.
    starting_str = "  t{1}_g{2}_z{3}_a{4}_v{5}"

    # Preserve the original GNU-parallel structure while using the current
    # stellar-parameter inputs.
    middle_str_new = (
        f" ::: {stellar_parameters.teff}"
        f" ::: {stellar_parameters.logg}"
        f" ::: {stellar_parameters.metallicity}"
        f" ::: {stellar_parameters.alpha}"
        f" ::: {stellar_parameters.vmic}"
    )

    space = "_"
    space_new = " ::: "
    curl_o = "{"
    curl_c = "}"

    placeholder_index = 6

    # Add fixed elements from the previous ASF iteration in the same order
    # passed by the caller.  This matches the original loop over q != p.
    for element_code, abundance_string in fixed_element_abundances.items():
        starting_str = (
            starting_str
            + space
            + element_code
            + curl_o
            + str(placeholder_index)
            + curl_c
        )

        # The extra blank after ":::" is intentional and follows the original
        # ASF command format expected by the external bash script.
        middle_str_new = middle_str_new + space_new + " " + abundance_string
        placeholder_index += 1

    # Add the variable element last, following the original ASF command
    # format expected by the external bash script.
    starting_str = (
        starting_str
        + space
        + variable_element_code
        + curl_o
        + str(placeholder_index)
        + curl_c
    )

    abund_str_long = " ".join(variable_abundance_strings)

    # Return the full GNU-parallel argument string passed to the external
    # Turbospectrum execution script.
    return starting_str + middle_str_new + space_new + " " + abund_str_long


def first_iteration_turbospectrum_commands(
    config: AutoSpecFitConfig,
    stellar_parameters: StellarParameters,
    species: SpeciesConfig,
) -> List[str]:
    """Build one Turbospectrum command string per target species for iteration 1."""
    abundance_strings = config.abundance_strings()
    return [
        build_turbospectrum_parallel_string(
            stellar_parameters=stellar_parameters,
            variable_element_code=element_code,
            variable_abundance_strings=abundance_strings,
        )
        for element_code in species.element_codes
    ]


def followup_iteration_turbospectrum_commands(
    config: AutoSpecFitConfig,
    stellar_parameters: StellarParameters,
    species: SpeciesConfig,
    previous_abundance_strings: List[str],
) -> List[str]:
    """Build one Turbospectrum command string per target species for iteration >= 2.

    For the target species, the abundance is varied over the abundance grid.
    All other species are fixed to the mean abundances inferred in the previous
    ASF iteration.
    """
    abundance_strings = config.abundance_strings()
    commands: List[str] = []

    for target_index, target_code in enumerate(species.element_codes):
        fixed_abundances: Dict[str, str] = {}
        for idx, element_code in enumerate(species.element_codes):
            if idx != target_index:
                fixed_abundances[element_code] = previous_abundance_strings[idx]

        commands.append(
            build_turbospectrum_parallel_string(
                stellar_parameters=stellar_parameters,
                variable_element_code=target_code,
                variable_abundance_strings=abundance_strings,
                fixed_element_abundances=fixed_abundances,
            )
        )

    return commands


def wait_for_model_files(model_paths: Iterable[Iterable[Path]], config: AutoSpecFitConfig) -> None:
    """Wait until all expected synthetic spectra exist on disk.

    This function allows ASF to pause after submitting Turbospectrum jobs and
    continue automatically once all required spectra have been generated.
    """
    if not config.wait_for_models:
        return

    flat_paths = [Path(path) for species_paths in model_paths for path in species_paths]

    for check_number in range(1, config.max_model_wait_checks + 1):
        missing = [path for path in flat_paths if not path.exists()]
        if not missing:
            LOGGER.info("All %d synthetic spectra are available.", len(flat_paths))
            return

        LOGGER.info(
            "Waiting for synthetic spectra: %d missing files at check %d/%d.",
            len(missing),
            check_number,
            config.max_model_wait_checks,
        )
        time.sleep(config.model_wait_seconds)

    missing_preview = "\n".join(str(path) for path in missing[:10])
    raise TimeoutError(
        "Synthetic spectra were not generated within the allowed wait time. "
        f"First missing files:\n{missing_preview}"
    )


def run_turbospectrum_command(command: str, runner: str, execution_prefix: str = "") -> None:
    """Submit one external Turbospectrum synthesis command.

    This preserves the original command structure:

        module load parallel; sbatch parallel ./run_TS_Interpolated_Model_H_band.sh <parallel string>

    The runner is kept as a string, not converted to ``Path`` for execution, so
    that a leading ``./`` is preserved exactly.
    """
    runner_path = Path(runner)
    if not runner_path.exists():
        raise FileNotFoundError(f"Turbospectrum execution script not found: {runner}")

    if execution_prefix:
        full_command = f"{execution_prefix} {runner} {command}"
    else:
        full_command = f"{runner} {command}"


    exit_status = os.system(full_command)
    if exit_status != 0:
        raise RuntimeError(
            f"Turbospectrum command failed with exit status {exit_status}:\n{full_command}"
        )


# -----------------------------------------------------------------------------
# Chi-square fitting and abundance-uncertainty estimation
# -----------------------------------------------------------------------------

def estimate_parabolic_chi2_uncertainty(
    abundances: np.ndarray,
    chi2_values: np.ndarray,
    fit_half_width: float = 0.10,
) -> Tuple[float, float]:
    """Estimate best abundance and uncertainty from a local parabolic fit.

    A quadratic function is fitted to chi-square values within
    ``sampled_minimum +/- fit_half_width``.  The 1-sigma error is estimated from
    ``chi2 = chi2_min + 1``.

    Returns ``(nan, nan)`` if the fit cannot be estimated reliably.
    """
    x = np.asarray(abundances, dtype=float)
    y = np.asarray(chi2_values, dtype=float)

    valid = np.isfinite(x) & np.isfinite(y)
    x = x[valid]
    y = y[valid]

    if len(x) < 3:
        return np.nan, np.nan

    order = np.argsort(x)
    x = x[order]
    y = y[order]

    sampled_minimum_index = int(np.argmin(y))
    sampled_best_abundance = x[sampled_minimum_index]

    local = np.abs(x - sampled_best_abundance) <= fit_half_width
    x_fit = x[local]
    y_fit = y[local]

    if len(x_fit) < 3:
        return sampled_best_abundance, np.nan

    try:
        a, b, c = np.polyfit(x_fit, y_fit, 2)
    except (np.linalg.LinAlgError, ValueError):
        return sampled_best_abundance, np.nan

    # A meaningful chi-square parabola must open upward.
    if not np.isfinite(a) or a <= 0:
        return sampled_best_abundance, np.nan

    best_abundance = -b / (2.0 * a)

    # Reject a vertex that lies outside the local fitting window.
    if best_abundance < np.min(x_fit) or best_abundance > np.max(x_fit):
        best_abundance = sampled_best_abundance
        chi2_min = y[sampled_minimum_index]
    else:
        chi2_min = a * best_abundance**2 + b * best_abundance + c

    # Solve the quadratic equation for chi2 = chi2_min + 1.
    roots = np.roots([a, b, c - (chi2_min + 1.0)])
    roots = np.real(roots[np.isreal(roots)])
    roots = np.sort(roots)

    if len(roots) < 2:
        return best_abundance, np.nan

    left_roots = roots[roots <= best_abundance]
    right_roots = roots[roots >= best_abundance]
    if len(left_roots) == 0 or len(right_roots) == 0:
        return best_abundance, np.nan

    abundance_error = 0.5 * (right_roots[0] - left_roots[-1])
    if not np.isfinite(abundance_error) or abundance_error <= 0:
        abundance_error = np.nan

    return best_abundance, abundance_error


def compute_line_chi2_curve(
    line_list: LineList,
    line_index: int,
    model_paths: List[Path],
    abundances: np.ndarray,
    lam_star: np.ndarray,
    flux_star: np.ndarray,
    err_flux_star: np.ndarray,
    config: AutoSpecFitConfig,
) -> Tuple[np.ndarray, np.ndarray]:
    """Compute chi-square values for one line over the abundance grid.

    Returns
    -------
    chi2_curve
        Array with one value per tested abundance.  Failed normalization/model
        points remain NaN.
    valid_abundances
        Abundance values for which a valid chi-square value was measured.
    """
    chi2_curve = np.full(len(abundances), np.nan)
    valid_abundances = []

    line_center = line_list.line_centers[line_index]
    radial_velocity = line_list.radial_velocities[line_index]
    fit_min = line_list.fit_min_wavelengths[line_index]
    fit_max = line_list.fit_max_wavelengths[line_index]

    for abundance_index, model_path in enumerate(model_paths):
        try:
            lam_model, flux_model = read_model_spectrum(model_path, config.gaussian_sigma_pixels)
        except FileNotFoundError:
            LOGGER.warning("Skipping missing model: %s", model_path)
            continue

        """AutoSpecNorm performs local normalization and returns the normalized
        observed flux, observed flux uncertainty normalized in the same way as 
        the observed flux, interpolated synthetic flux,  and the normalization
        uncertainty (delta).
        """
        (
            lam_star_cut,
            _flux_star_cut,
            flux_interp_model_cut,
            flux_star_cut_normalized,
            _upper_flux_star_cut_normalized,
            _lower_flux_star_cut_normalized,
            err_flux_star_cut_normalized,
            lam_cut_work,
            _flux_star_cut_work,
            _flux_interp_model_cut_work,
            delta,
            flag,
        ) = AutoSpecNorm_Regions(
            line_center,
            config.lam_diff_large,
            radial_velocity,
            lam_star,
            flux_star,
            err_flux_star,
            lam_model,
            flux_model,
            config.limit_model,
            config.limit_star,
            config.peak_index_model,
            config.peak_index_star,
            config.autospecnorm_iteration_number,
        )

        # Reject cases where AutoSpecNorm could not identify usable continuum
        # points on both sides of the fitted line.
        has_left_point = np.any(lam_cut_work < line_center)
        has_right_point = np.any(lam_cut_work > line_center)
        if not has_left_point or not has_right_point or flag == 0:
            continue

        fit_mask = (lam_star_cut >= fit_min) & (lam_star_cut <= fit_max)
        if not np.any(fit_mask):
            continue

        obs = flux_star_cut_normalized[fit_mask]
        obs_err = err_flux_star_cut_normalized[fit_mask]
        model = flux_interp_model_cut[fit_mask]
        delta_fit = delta[fit_mask]

        # Chi-square includes both the observational flux uncertainty and the
        # normalization uncertainty returned by AutoSpecNorm.
        variance = obs_err**2 + delta_fit**2
        valid_variance = variance > 0
        if not np.any(valid_variance):
            continue

        chi2_value = np.sum(((obs[valid_variance] - model[valid_variance]) ** 2) / variance[valid_variance])
        chi2_curve[abundance_index] = chi2_value
        valid_abundances.append(abundances[abundance_index])

    return chi2_curve, np.asarray(valid_abundances, dtype=float)


def best_grid_abundance(abundances: np.ndarray, chi2_curve: np.ndarray) -> float:
    """Return the grid abundance corresponding to the minimum chi-square."""
    valid = np.isfinite(chi2_curve)
    if not np.any(valid):
        return np.nan
    valid_indices = np.where(valid)[0]
    best_index = valid_indices[int(np.argmin(chi2_curve[valid]))]
    return float(abundances[best_index])


# -----------------------------------------------------------------------------
# Line rejection and species-level abundance combination
# -----------------------------------------------------------------------------

def reject_edge_or_known_outlier_lines(
    line_abundances: np.ndarray,
    line_centers: np.ndarray,
    species_index: int,
    config: AutoSpecFitConfig,
) -> Tuple[np.ndarray, np.ndarray]:
    """Remove lines whose best-fit abundance falls at problematic grid edges."""
    valid = np.isfinite(line_abundances)

    if species_index == 0:
        # OH has a known low-abundance tail in this use case, so a slightly
        # higher lower bound is used.
        abundance_mask = (
            (line_abundances > config.oh_lower_rejection_limit)
            & (line_abundances < config.upper_rejection_limit)
        )
    else:
        abundance_mask = (
            (line_abundances > config.generic_lower_rejection_limit)
            & (line_abundances < config.upper_rejection_limit)
        )

    mask = valid & abundance_mask
    return line_abundances[mask], line_centers[mask]


def sigma_clip_line_abundances(abundances: np.ndarray, sigma_clipping: float) -> np.ndarray:
    """Apply conservative sigma clipping to line-by-line abundances.

    For small numbers of lines, no clipping is applied.  This follows the
    original ASF logic and avoids over-clipping species with few diagnostics.
    """
    abundances = np.asarray(abundances, dtype=float).ravel()
    abundances = abundances[np.isfinite(abundances)]

    if len(abundances) <= 1:
        return abundances
    if len(np.unique(abundances)) == 1:
        return abundances
    if len(abundances) < 11:
        return abundances

    mean = np.mean(abundances)
    std = np.std(abundances, ddof=1)
    if not np.isfinite(std) or std == 0:
        return abundances

    keep = np.abs(abundances - mean) < sigma_clipping * std
    return abundances[keep]


def median_distance_weighted_mean(abundances: np.ndarray) -> float:
    """Return the ASF median-distance weighted mean abundance.

    Lines closer to the median abundance receive higher weight.  The distance
    from the median is binned in units of 0.1 times the standard deviation,
    reproducing the weighting philosophy of the original ASF script.
    """
    abundances = np.asarray(abundances, dtype=float).ravel()
    abundances = abundances[np.isfinite(abundances)]

    if len(abundances) == 0:
        return np.nan
    if len(abundances) == 1:
        return float(abundances[0])

    std = np.std(abundances, ddof=1)
    median = np.median(abundances)
    distances = np.abs(abundances - median)

    if not np.isfinite(std) or std == 0:
        weights = np.ones_like(abundances)
    else:
        distance_bins = np.full_like(abundances, fill_value=5.0, dtype=float)
        for idx, distance in enumerate(distances):
            for bin_index in range(45):
                lower = bin_index * 0.1 * std
                upper = (bin_index + 1) * 0.1 * std
                if lower <= distance < upper:
                    distance_bins[idx] = (bin_index + 1) * 0.1
                    break
        weights = 1.0 / distance_bins

    return float(np.sum(abundances * weights) / np.sum(weights))


def combine_species_line_abundances(
    line_results: List[LineFitResult],
    species_index: int,
    config: AutoSpecFitConfig,
) -> Tuple[np.ndarray, float, float]:
    """Combine line-by-line abundances into a species-level abundance."""
    line_abundances = np.asarray([result.best_abundance_grid for result in line_results], dtype=float)
    line_centers = np.asarray([result.line_center for result in line_results], dtype=float)

    abundance_filtered, _line_centers_filtered = reject_edge_or_known_outlier_lines(
        line_abundances,
        line_centers,
        species_index,
        config,
    )
    clipped = sigma_clip_line_abundances(abundance_filtered, config.sigma_clipping)
    mean = median_distance_weighted_mean(clipped)
    rounded_mean = round(mean, 3) if np.isfinite(mean) else np.nan
    return clipped, mean, rounded_mean


def fit_species_in_iteration(
    iteration_id: int,
    species_index: int,
    species: SpeciesConfig,
    line_list: LineList,
    species_model_paths: List[Path],
    lam_star: np.ndarray,
    flux_star: np.ndarray,
    err_flux_star: np.ndarray,
    config: AutoSpecFitConfig,
    abundance_grid: np.ndarray,
    log_handle=None,
) -> SpeciesIterationResult:
    """Fit all selected lines for one species in one iteration.

    If a log file handle is provided, each line abundance is written
    immediately after it is measured. This reproduces the behavior of
    the original ASF script and allows progress to be monitored during
    long abundance iterations.
    """
    species_name = species.species_names[species_index]
    element_name = species.element_names[species_index]
    LOGGER.info("Iteration %d | fitting %s (%d lines)", iteration_id, species_name, line_list.n_lines)

    if log_handle is not None:
        log_handle.write(f"{element_name}\n")
        log_handle.flush()

    line_results: List[LineFitResult] = []

    for line_index in range(line_list.n_lines):
        chi2_curve, _valid_abundances = compute_line_chi2_curve(
            line_list=line_list,
            line_index=line_index,
            model_paths=species_model_paths,
            abundances=abundance_grid,
            lam_star=lam_star,
            flux_star=flux_star,
            err_flux_star=err_flux_star,
            config=config,
        )

        best_grid = best_grid_abundance(abundance_grid, chi2_curve)
        best_parabola, abundance_error = estimate_parabolic_chi2_uncertainty(
            abundance_grid,
            chi2_curve,
            fit_half_width=config.parabolic_fit_half_width,
        )

        line_result = LineFitResult(
            species_name=species_name,
            line_index=line_index,
            line_center=float(line_list.line_centers[line_index]),
            best_abundance_grid=best_grid,
            best_abundance_parabola=best_parabola,
            abundance_error=abundance_error,
            chi2_curve=chi2_curve,
        )
        line_results.append(line_result)

        # Write this line immediately, rather than waiting for the full
        # iteration to finish. This matches the older/original ASF behavior.
        if log_handle is not None:
            log_handle.write(
                f"{line_result.line_center:.6f} "
                f"{line_result.best_abundance_parabola:.6f} "
                f"{line_result.best_abundance_grid:.6f}\n\n"
            )
            log_handle.flush()

    clipped, mean, rounded_mean = combine_species_line_abundances(line_results, species_index, config)
    LOGGER.info(
        "Iteration %d | %s mean abundance = %.3f from %d clipped/accepted lines",
        iteration_id,
        species_name,
        rounded_mean,
        len(clipped),
    )

    return SpeciesIterationResult(
        species_name=species_name,
        element_name=element_name,
        line_results=line_results,
        clipped_line_abundances=clipped,
        mean_abundance=mean,
        rounded_mean_abundance=rounded_mean,
    )



def run_iteration(
    iteration_id: int,
    model_paths: List[List[Path]],
    species: SpeciesConfig,
    line_lists: List[LineList],
    lam_star: np.ndarray,
    flux_star: np.ndarray,
    err_flux_star: np.ndarray,
    config: AutoSpecFitConfig,
    abundance_grid: np.ndarray,
    turbospectrum_commands: Optional[List[str]] = None,
    log_handle=None,
) -> List[SpeciesIterationResult]:
    """Run one complete ASF abundance iteration.

    The iteration can optionally submit Turbospectrum jobs, wait for the
    expected synthetic spectra, fit all selected lines for all species, write
    diagnostic output files, and return the species-level abundance results.
    """
    run_ts_this_iteration = config.run_ts_by_iteration.get(iteration_id, config.run_turbospectrum)

    if run_ts_this_iteration:
        if config.turbospectrum_runner is None:
            raise ValueError(
                "config.run_turbospectrum=True, but config.turbospectrum_runner is not defined."
            )
        if not turbospectrum_commands:
            raise ValueError(
                "config.run_turbospectrum=True, but no Turbospectrum command strings were provided."
            )

        for command in turbospectrum_commands:
            run_turbospectrum_command(
                command=command,
                runner=config.turbospectrum_runner,
                execution_prefix=config.turbospectrum_execution_prefix,
            )
    else:
        LOGGER.info(
            "Skipping Turbospectrum launch for iteration %d; using existing synthetic spectra.",
            iteration_id,
        )

    wait_for_model_files(model_paths, config)

    if log_handle is not None:
        if iteration_id > 1:
            log_handle.write("--------------------------------------\n")
        log_handle.write(f"Iteration {iteration_id}\n")
        log_handle.write("*******************\n\n")
        log_handle.flush()

    species_results: List[SpeciesIterationResult] = []
    for species_index in range(species.n_species):
        result = fit_species_in_iteration(
            iteration_id=iteration_id,
            species_index=species_index,
            species=species,
            line_list=line_lists[species_index],
            species_model_paths=model_paths[species_index],
            lam_star=lam_star,
            flux_star=flux_star,
            err_flux_star=err_flux_star,
            config=config,
            abundance_grid=abundance_grid,
            log_handle=log_handle,
        )
        species_results.append(result)

    all_line_results = [line for result in species_results for line in result.line_results]
    write_iteration_chi2_table(iteration_id, abundance_grid, all_line_results, config.output_dir)
    write_iteration_abundance_error_table(iteration_id, all_line_results, config.output_dir)

    mean_abundances = np.asarray([result.rounded_mean_abundance for result in species_results], dtype=float)
    write_species_mean_table(iteration_id, species, mean_abundances, config)

    return species_results


def convergence_rule_for_iteration(
    iteration_id: int,
    config: AutoSpecFitConfig,
) -> Tuple[float, int, str]:
    """Return the convergence tolerance and allowed non-converged species count.

    The convergence rule becomes progressively more flexible with iteration
    number. Early iterations require all species to converge tightly. Later
    iterations allow one species to remain non-converged, in which case that
    species is treated as oscillating and its final abundance is estimated
    from its late-iteration history.
    """
    if iteration_id < config.intermediate_convergence_start_iteration:
        return config.early_convergence_tolerance, 0, "strict early convergence"

    if iteration_id < config.late_convergence_start_iteration:
        return config.intermediate_convergence_tolerance, 1, "intermediate convergence"

    return config.late_convergence_tolerance, 1, "late convergence"


def evaluate_convergence_status(
    change: np.ndarray,
    iteration_id: int,
    config: AutoSpecFitConfig,
) -> Tuple[bool, List[int], float, str]:
    """Evaluate ASF convergence for the current iteration.

    Returns
    -------
    converged
        True when the current iteration satisfies the tiered convergence rule.
    non_converged_indices
        Indices of species that do not satisfy the active convergence
        tolerance.
    active_tolerance
        Convergence tolerance used for this iteration.
    convergence_mode
        Text label describing the active convergence regime.
    """
    finite = np.isfinite(change)
    if not np.all(finite):
        active_tolerance, _max_non_converged, convergence_mode = (
            convergence_rule_for_iteration(iteration_id, config)
        )
        return False, [], active_tolerance, convergence_mode

    active_tolerance, max_non_converged, convergence_mode = (
        convergence_rule_for_iteration(iteration_id, config)
    )

    converged_mask = change <= active_tolerance
    non_converged_indices = np.where(~converged_mask)[0].astype(int).tolist()
    converged = len(non_converged_indices) <= max_non_converged

    return converged, non_converged_indices, active_tolerance, convergence_mode


def late_history_median(
    history: np.ndarray,
    window: int,
) -> Tuple[float, np.ndarray]:
    """Return the median abundance from the final finite iteration values.

    This statistic is used for species that do not satisfy the active
    convergence tolerance but are treated as oscillating or not fully
    converged. Only the final ``window`` finite iteration abundances are used,
    so early iterations do not influence the adopted final value.
    """
    history = np.asarray(history, dtype=float)
    finite_history = history[np.isfinite(history)]

    if len(finite_history) == 0:
        return np.nan, finite_history

    late_values = finite_history[-window:]
    return float(np.median(late_values)), late_values


def apply_late_history_statistics(
    final_not_rounded: np.ndarray,
    final_rounded: np.ndarray,
    indices: List[int],
    mean_history: np.ndarray,
    iteration_id: int,
    species: SpeciesConfig,
    config: AutoSpecFitConfig,
    log_handle,
    notes: List[str],
    context: str,
) -> None:
    """Apply late-history median statistics to selected species.

    Parameters
    ----------
    final_not_rounded, final_rounded
        Final abundance arrays updated in place.
    indices
        Species indices for which the final abundance should be replaced by
        the median of the final finite iteration values.
    mean_history
        Species-by-iteration abundance history.
    iteration_id
        Current ASF iteration number.
    context
        Short description written to the log file explaining why the
        late-history statistic was used.
    """
    for species_index in indices:
        element_name = species.element_names[species_index]
        adopted_value, late_values = late_history_median(
            mean_history[species_index, :iteration_id],
            config.final_statistics_window,
        )

        if np.isfinite(adopted_value):
            final_not_rounded[species_index] = adopted_value
            final_rounded[species_index] = np.round(adopted_value, 2)

            late_values_text = ", ".join(f"{value:+.3f}" for value in late_values)
            note = (
                f"Iteration {iteration_id}: {element_name} {context}; final "
                f"{element_name} abundance set to the median of the final "
                f"{len(late_values)} finite iteration values "
                f"({late_values_text}; median = {adopted_value:+.3f})."
            )
        else:
            note = (
                f"Iteration {iteration_id}: {element_name} {context}, but no "
                f"finite abundance history was available for replacement."
            )

        LOGGER.warning(note)
        log_handle.write(f"# {note}\n")
        log_handle.flush()
        notes.append(note)


# -----------------------------------------------------------------------------
# Main pipeline
# -----------------------------------------------------------------------------

def run_autospecfit_abundance_pipeline(
    config: AutoSpecFitConfig,
    stellar_parameters: StellarParameters,
    species: SpeciesConfig,
) -> None:
    """Run the AutoSpecFit-Abund v1.0 pipeline.

    This function coordinates the full abundance workflow: reading inputs,
    building model paths and Turbospectrum commands, running abundance
    iterations, checking convergence, and writing output products.
    """
    config.output_dir.mkdir(parents=True, exist_ok=True)

    # Convert the configured abundance grid to a numerical array used in
    # chi-square fitting and parabolic uncertainty estimation.
    abundance_grid = np.asarray(config.abundance_values, dtype=float)

    # Read the observed spectrum and apply the configured wavelength scaling.
    lam_star, flux_star, err_flux_star = read_observed_spectrum(
        config.observed_spectrum_file,
        config.observed_wavelength_scale,
    )
    # Read the selected diagnostic lines for every species.
    line_lists = read_all_line_lists(config, species)

    # Store abundance history. Each column corresponds to one ASF iteration.
    n_total_iterations = 1 + config.n_followup_iterations
    mean_history = np.full((species.n_species, n_total_iterations), np.nan)
    rounded_history = np.full((species.n_species, n_total_iterations), np.nan)

    # Record cases where a NaN abundance is replaced when constructing the
    # fixed-abundance list for the next iteration.
    nan_replacement_notes: List[str] = []

    log_path = Path(config.output_dir) / config.iteration_log_file
    with open(log_path, "w", buffering=1) as log_handle:
        log_handle.write("LineCenter BestFit_Abundance_PolyFit BestFit_Abundance_Original\n")
        log_handle.write("==================================================================\n")

        # First iteration: only the target element is varied in each model grid.
        LOGGER.info("Starting AutoSpecFit-Abund iteration 1")
        model_paths = first_iteration_model_paths(config, stellar_parameters, species)
        turbospectrum_commands = first_iteration_turbospectrum_commands(
            config=config,
            stellar_parameters=stellar_parameters,
            species=species,
        )
        results = run_iteration(
            iteration_id=1,
            model_paths=model_paths,
            species=species,
            line_lists=line_lists,
            lam_star=lam_star,
            flux_star=flux_star,
            err_flux_star=err_flux_star,
            config=config,
            abundance_grid=abundance_grid,
            turbospectrum_commands=turbospectrum_commands,
            log_handle=log_handle,
        )

        mean_history[:, 0] = [result.mean_abundance for result in results]
        rounded_history[:, 0] = [result.rounded_mean_abundance for result in results]

        # Follow-up iterations: for each target element, fix all other element
        # abundances to the values inferred in the previous iteration.
        for followup_index in range(config.n_followup_iterations):
            iteration_id = followup_index + 2
            LOGGER.info("Starting AutoSpecFit-Abund iteration %d", iteration_id)

            # The previous iteration abundances become the fixed abundances
            # for all non-target elements in the next synthetic spectral grid.
            previous_abundance_strings = []
            current_nan_replacement_notes: List[str] = []

            for species_index, value in enumerate(
                rounded_history[:, iteration_id - 2]
            ):
                element_name = species.element_names[species_index]

                if np.isfinite(value):
                    previous_abundance_strings.append(f"{value:+.3f}")
                else:
                    earlier_values = rounded_history[
                        species_index, : iteration_id - 2
                    ]
                    finite_earlier_values = earlier_values[
                        np.isfinite(earlier_values)
                    ]

                    if len(finite_earlier_values) > 0:
                        replacement_value = float(finite_earlier_values[-1])
                        previous_abundance_strings.append(
                            f"{replacement_value:+.3f}"
                        )
                        note = (
                            f"Iteration {iteration_id}: {element_name} abundance "
                            f"from iteration {iteration_id - 1} is NaN; using "
                            f"{replacement_value:+.3f} from the most recent "
                            f"valid previous iteration to generate models."
                        )
                    else:
                        previous_abundance_strings.append("+0.000")
                        note = (
                            f"Iteration {iteration_id}: {element_name} abundance "
                            f"from iteration {iteration_id - 1} is NaN and no "
                            f"previous valid abundance exists; using +0.000 "
                            f"to generate models."
                        )

                    LOGGER.warning(note)
                    log_handle.write(f"# {note}\n")
                    log_handle.flush()
                    current_nan_replacement_notes.append(note)
                    nan_replacement_notes.append(note)

            append_nan_replacement_notes_to_mean_file(
                iteration_id=iteration_id - 1,
                notes=current_nan_replacement_notes,
                config=config,
            )

            model_paths = followup_iteration_model_paths(
                config,
                stellar_parameters,
                species,
                previous_abundance_strings,
            )
            turbospectrum_commands = followup_iteration_turbospectrum_commands(
                config=config,
                stellar_parameters=stellar_parameters,
                species=species,
                previous_abundance_strings=previous_abundance_strings,
            )
            results = run_iteration(
                iteration_id=iteration_id,
                model_paths=model_paths,
                species=species,
                line_lists=line_lists,
                lam_star=lam_star,
                flux_star=flux_star,
                err_flux_star=err_flux_star,
                config=config,
                abundance_grid=abundance_grid,
                turbospectrum_commands=turbospectrum_commands,
                log_handle=log_handle,
            )

            mean_history[:, iteration_id - 1] = [result.mean_abundance for result in results]
            rounded_history[:, iteration_id - 1] = [result.rounded_mean_abundance for result in results]

            # Evaluate convergence using a tiered set of criteria.
            #
            # Iterations 2-6 require all species to converge using the strict
            # early tolerance. Iterations 7-8 allow one non-converged species
            # using the intermediate tolerance. Iterations 9-12 use the late
            # tolerance and also allow one non-converged species. Any allowed
            # non-converged species is assigned a final abundance using the
            # median of its final finite iteration values.
            change = np.abs(mean_history[:, iteration_id - 1] - mean_history[:, iteration_id - 2])
            (
                converged,
                non_converged_indices,
                active_tolerance,
                convergence_mode,
            ) = evaluate_convergence_status(
                change,
                iteration_id,
                config,
            )

            # If this is the maximum iteration and the tiered convergence
            # criteria are still not satisfied, write a final abundance table
            # anyway. Species that remain non-converged with respect to the
            # late tolerance are assigned the median of their final finite
            # iteration abundances.
            reached_maximum_iteration = iteration_id == n_total_iterations
            forced_final_iteration = False
            if not converged and reached_maximum_iteration:
                forced_final_iteration = True
                active_tolerance = config.late_convergence_tolerance
                convergence_mode = "maximum-iteration finalization"
                non_converged_indices = np.where((~np.isfinite(change)) | (change > active_tolerance))[0].astype(int).tolist()
                converged = True

            if converged:
                final_not_rounded = mean_history[:, iteration_id - 1].copy()
                final_rounded = np.round(rounded_history[:, iteration_id - 1], 2)

                if non_converged_indices:
                    if forced_final_iteration:
                        context = (
                            f"did not satisfy the final convergence tolerance "
                            f"({active_tolerance:.3f} dex) at the maximum "
                            f"iteration"
                        )
                    else:
                        context = (
                            f"was treated as oscillating under the "
                            f"{convergence_mode} criterion "
                            f"({active_tolerance:.3f} dex)"
                        )

                    apply_late_history_statistics(
                        final_not_rounded=final_not_rounded,
                        final_rounded=final_rounded,
                        indices=non_converged_indices,
                        mean_history=mean_history,
                        iteration_id=iteration_id,
                        species=species,
                        config=config,
                        log_handle=log_handle,
                        notes=nan_replacement_notes,
                        context=context,
                    )

                if forced_final_iteration:
                    note = (
                        f"Maximum iteration {iteration_id} reached before a "
                        f"tiered convergence criterion was satisfied. Final "
                        f"abundances were written using the last iteration for "
                        f"converged species and late-history medians for "
                        f"non-converged species."
                    )
                elif non_converged_indices:
                    note = (
                        f"Convergence accepted at iteration {iteration_id} "
                        f"under the {convergence_mode} criterion: all but "
                        f"{len(non_converged_indices)} species satisfied "
                        f"the {active_tolerance:.3f} dex tolerance."
                    )
                else:
                    note = (
                        f"Convergence accepted at iteration {iteration_id} "
                        f"under the {convergence_mode} criterion: all species "
                        f"satisfied the {active_tolerance:.3f} dex tolerance."
                    )

                LOGGER.info(note)
                log_handle.write(f"# {note}\n")
                log_handle.flush()
                nan_replacement_notes.append(note)

                final_errors = species_abundance_errors_from_iteration(results)
                write_final_abundance_table(
                    final_not_rounded=final_not_rounded,
                    final_rounded=final_rounded,
                    final_errors=final_errors,
                    species=species,
                    config=config,
                    nan_replacement_notes=nan_replacement_notes,
                )
                return

        # This block is normally not reached because the maximum-iteration
        # finalization step inside the loop writes a final table at the last
        # iteration. It is retained as a safety fallback.
        LOGGER.warning(
            "Iteration loop ended without an accepted convergence condition; "
            "writing the last available iteration as the final result."
        )
        final_errors = species_abundance_errors_from_iteration(results)
        write_final_abundance_table(
            final_not_rounded=mean_history[:, -1],
            final_rounded=np.round(rounded_history[:, -1], 2),
            final_errors=final_errors,
            species=species,
            config=config,
            nan_replacement_notes=nan_replacement_notes,
        )


# -----------------------------------------------------------------------------
# Command-line entry point
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    # Edit these three objects for a new star or create a small wrapper script
    # that imports this module and passes a custom configuration.
    CONFIG = AutoSpecFitConfig(
        run_ts_by_iteration={},
    )
    STELLAR_PARAMETERS = StellarParameters()
    SPECIES = SpeciesConfig()

    run_autospecfit_abundance_pipeline(CONFIG, STELLAR_PARAMETERS, SPECIES)
